// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1) {
  return window['go']['app']['App']['ChatWithAI'](arg1);
}

export function ChatWithSession(arg1, arg2) {
  return window['go']['app']['App']['ChatWithSession'](arg1, arg2);
}

export function CleanupOutputFiles(arg1) {
  return window['go']['app']['App']['CleanupOutputFiles'](arg1);
}

export function CleanupTempFiles(arg1) {
  return window['go']['app']['App']['CleanupTempFiles'](arg1);
}

export function ClearClipboardHistory() {
  return window['go']['app']['App']['ClearClipboardHistory']();
}

export function CollapseWindow() {
  return window['go']['app']['App']['CollapseWindow']();
}

export function CopyOutputFile(arg1, arg2) {
  return window['go']['app']['App']['CopyOutputFile'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['app']['App']['CopyToClipboard'](arg1);
}

export function CreateNewChatSession() {
  return window['go']['app']['App']['CreateNewChatSession']();
}

export function DeleteChatSession(arg1) {
  return window['go']['app']['App']['DeleteChatSession'](arg1);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['app']['App']['DeleteClipboardItem'](arg1);
}

export function DeletePlugin(arg1) {
  return window['go']['app']['App']['DeletePlugin'](arg1);
}

export function ExecutePlugin(arg1, arg2) {
  return window['go']['app']['App']['ExecutePlugin'](arg1, arg2);
}

export function ExpandWindow(arg1, arg2) {
  return window['go']['app']['App']['ExpandWindow'](arg1, arg2);
}

export function GeneratePlugin(arg1) {
  return window['go']['app']['App']['GeneratePlugin'](arg1);
}

export function GetAllConfigs() {
  return window['go']['app']['App']['GetAllConfigs']();
}

export function GetAllPlugins() {
  return window['go']['app']['App']['GetAllPlugins']();
}

export function GetAllTags() {
  return window['go']['app']['App']['GetAllTags']();
}

export function GetChatSession(arg1) {
  return window['go']['app']['App']['GetChatSession'](arg1);
}

export function GetClipboardItem(arg1) {
  return window['go']['app']['App']['GetClipboardItem'](arg1);
}

export function GetClipboardItems(arg1, arg2) {
  return window['go']['app']['App']['GetClipboardItems'](arg1, arg2);
}

export function GetConfig(arg1) {
  return window['go']['app']['App']['GetConfig'](arg1);
}

export function GetConfigurableKeys() {
  return window['go']['app']['App']['GetConfigurableKeys']();
}

export function GetOutputFileBase64(arg1) {
  return window['go']['app']['App']['GetOutputFileBase64'](arg1);
}

export function GetPluginExecuteCode(arg1) {
  return window['go']['app']['App']['GetPluginExecuteCode'](arg1);
}

export function GetPluginInfo(arg1) {
  return window['go']['app']['App']['GetPluginInfo'](arg1);
}

export function ListChatSessions() {
  return window['go']['app']['App']['ListChatSessions']();
}

export function OpenFileDialog(arg1) {
  return window['go']['app']['App']['OpenFileDialog'](arg1);
}

export function ResetConfig(arg1) {
  return window['go']['app']['App']['ResetConfig'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2);
}

export function SearchClipboardItems(arg1, arg2) {
  return window['go']['app']['App']['SearchClipboardItems'](arg1, arg2);
}

export function SetConfig(arg1, arg2) {
  return window['go']['app']['App']['SetConfig'](arg1, arg2);
}

export function SetConfigs(arg1) {
  return window['go']['app']['App']['SetConfigs'](arg1);
}

export function SetProgressCallback(arg1) {
  return window['go']['app']['App']['SetProgressCallback'](arg1);
}

export function TestTagConfiguration(arg1) {
  return window['go']['app']['App']['TestTagConfiguration'](arg1);
}

export function ToggleClipboardFavorite(arg1) {
  return window['go']['app']['App']['ToggleClipboardFavorite'](arg1);
}

export function TogglePluginStatus(arg1) {
  return window['go']['app']['App']['TogglePluginStatus'](arg1);
}

export function UpdateClipboardItem(arg1) {
  return window['go']['app']['App']['UpdateClipboardItem'](arg1);
}

export function UploadTempFile(arg1, arg2) {
  return window['go']['app']['App']['UploadTempFile'](arg1, arg2);
}

export function ValidateConfigs() {
  return window['go']['app']['App']['ValidateConfigs']();
}
