// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {app} from '../models';
import {services} from '../models';

export function ChatWithAI(arg1:string):Promise<string>;

export function ChatWithSession(arg1:string,arg2:string):Promise<models.ChatResponse>;

export function CleanupOutputFiles(arg1:Array<string>):Promise<void>;

export function CleanupTempFiles(arg1:Array<string>):Promise<void>;

export function ClearClipboardHistory():Promise<void>;

export function CollapseWindow():Promise<void>;

export function CopyOutputFile(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:number):Promise<void>;

export function CreateNewChatSession():Promise<string>;

export function DeleteChatSession(arg1:string):Promise<void>;

export function DeleteClipboardItem(arg1:number):Promise<void>;

export function DeletePlugin(arg1:number):Promise<void>;

export function ExecutePlugin(arg1:number,arg2:string):Promise<string>;

export function ExpandWindow(arg1:number,arg2:number):Promise<void>;

export function GeneratePlugin(arg1:app.PluginCreationRequest):Promise<models.Plugin>;

export function GetAllConfigs():Promise<string>;

export function GetAllPlugins():Promise<Array<models.Plugin>>;

export function GetAllTags():Promise<Array<models.Tag>>;

export function GetChatSession(arg1:string):Promise<models.ChatSession>;

export function GetClipboardItem(arg1:number):Promise<models.ClipboardItem>;

export function GetClipboardItems(arg1:number,arg2:number):Promise<Array<models.ClipboardItem>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetConfigurableKeys():Promise<string>;

export function GetOutputFileBase64(arg1:string):Promise<string>;

export function GetPluginExecuteCode(arg1:number):Promise<string>;

export function GetPluginInfo(arg1:number):Promise<string>;

export function ListChatSessions():Promise<Array<models.ChatSession>>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function ResetConfig(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SearchClipboardItems(arg1:string,arg2:number):Promise<Array<models.ClipboardItem>>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetConfigs(arg1:string):Promise<void>;

export function SetProgressCallback(arg1:app.ProgressCallback):Promise<void>;

export function TestTagConfiguration(arg1:Array<number>):Promise<services.PluginGenerationConfig>;

export function ToggleClipboardFavorite(arg1:number):Promise<void>;

export function TogglePluginStatus(arg1:number):Promise<void>;

export function UpdateClipboardItem(arg1:models.ClipboardItem):Promise<void>;

export function UploadTempFile(arg1:string,arg2:string):Promise<string>;

export function ValidateConfigs():Promise<string>;
